services:
  postgres-db:
    image: postgres:15
    container_name: vanvan-postgres
    restart: always
    environment:
      POSTGRES_DB: SistemaVan
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
    container_name: vanvan-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/SistemaVan
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none

  frontend:
    build:
      context: ./frontend
    container_name: vanvan-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  pg_data: